name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update; sudo apt-get install libcurl4-openssl-dev; sudo apt install libeigen3-dev;
    - name: prepare htslib
      run: git clone --branch=develop --recursive https://github.com/samtools/htslib.git;cd htslib; make;cd ..;
    - name: make
      run: export HTSSRC=`pwd`/htslib; make
    - name: make
      run: make
    - name: make test
      run:  make test
